# Generated by Django 2.1.4 on 2018-12-22 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('content', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('created', 'Created'), ('countersigned', 'Countersigned'), ('rewrited', 'Rewrited'), ('reviewed', 'Reviewed'), ('signed', 'Signed')], default='created', max_length=50)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clients', models.ManyToManyField(to='contract_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Countersign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contract_app.Contract')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contract_app.Contract')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_read_contracts', models.BooleanField(default=False)),
                ('can_write_contracts', models.BooleanField(default=False)),
                ('can_countersign', models.BooleanField(default=False)),
                ('can_set_countersign', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('can_set_review', models.BooleanField(default=False)),
                ('can_sign', models.BooleanField(default=False)),
                ('can_set_sign', models.BooleanField(default=False)),
                ('can_read_users', models.BooleanField(default=False)),
                ('can_write_users', models.BooleanField(default=False)),
                ('can_read_roles', models.BooleanField(default=False)),
                ('can_write_roles', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contract_app.Contract')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='users_countersign',
            field=models.ManyToManyField(related_name='contracts_countersign', through='contract_app.Countersign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='users_review',
            field=models.ManyToManyField(related_name='contracts_review', through='contract_app.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='users_sign',
            field=models.ManyToManyField(related_name='contracts_sign', through='contract_app.Sign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='contract_app.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='sign',
            unique_together={('user', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='countersign',
            unique_together={('user', 'contract')},
        ),
    ]
