# Generated by Django 2.1.4 on 2018-12-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countersign',
            unique_together={('user', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='sign',
            unique_together={('user', 'contract')},
        ),
    ]
