# Generated by Django 2.1.4 on 2018-12-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countersign',
            name='contract',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='countersigns', to='contract_app.Contract'),
        ),
        migrations.AlterField(
            model_name='countersign',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='countersigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='contract_app.Role'),
        ),
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contract_app.Contract'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sign',
            name='contract',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='contract_app.Contract'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to=settings.AUTH_USER_MODEL),
        ),
    ]
