# Generated by Django 2.1.4 on 2018-12-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0003_auto_20181223_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_set_countersign',
            new_name='can_distribute',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_set_review',
            new_name='can_manage_clients',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_set_sign',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('distributed', 'distributed'), ('countersigned', 'countersigned'), ('rewrited', 'rewrited'), ('reviewed', 'reviewed'), ('signed', 'signed')], default='created', max_length=50),
        ),
    ]
