# Generated by Django 2.1.4 on 2018-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0004_auto_20181224_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('distributed', 'distributed'), ('countersigned', 'countersigned'), ('rewrited', 'rewrited'), ('reviewed', 'reviewed'), ('signed', 'signed')], default='created', help_text='created (default), distributed, countersigned, rewrited, reviewed, signed', max_length=50),
        ),
    ]
